Board/BoardSystem/Models/Board.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BoardSystem.Models
{
    public class Board
    {
        [Key]
        public int BoardNum { get; set; }

        [Required(ErrorMessage = "タイトルを入力してください。")]
        public string BoardTitle { get; set; }

        [Required(ErrorMessage = "内容を入力してください。")]
        public string BoardContents { get; set; }

        
        public string UserId { get; set; }

        public int BoardViews { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime BoardDate { get; set; }

        [ForeignKey("UserId")]
        public virtual User User { get; set; }
    }
}

Board/BoardSystem/Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BoardSystem.DataContext;
using BoardSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BoardSystem.Controllers
{
    public class BoardController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            if(HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            //using (var db = new BoardSystemContext())
            //{
            //    List<Board> list;
            //    try
            //    {
            //        list = getList(0);
            //    }
            //    catch
            //    {
            //        return RedirectToAction("Error", "Home");
            //    }

            //    return View(list);
            //}
            return View();
        }

        //public JsonResult Paging(int page)
        //{
        //    List<Board> list = null;
        //    list = getList(page);
           
        //    JArray json = new JArray();
        //    foreach (Board board in list)
        //    {
        //        String jori = "{";
        //        jori += "\"No\":\"" + board.BoardNum + "\",";
        //        jori += "\"Title\":\"" + board.BoardTitle + "\",";
        //        jori += "\"User\":\"" + board.UserId + "\",";
        //        jori += "\"Date\":\"" + board.BoardDate + "\",";
        //        jori += "\"Views\":\"" + board.BoardViews + "\"";
        //        jori += "}";
        //        JObject jtmp = JObject.Parse(jori);
        //        json.Add(jtmp);
        //    }

        //    return new JsonResult(json);
            
        //}

        //private List<Board> getList(int page)
        //{
        //    using (var db = new BoardSystemContext())
        //    {
        //        List<Board> list;
        //        if (page == 0)
        //        {
        //            list = db.Boards.OrderByDescending(s => s.BoardNum).Take(20).ToList();
        //        }
        //        else
        //        {
        //            list = db.Boards.OrderByDescending(s => s.BoardNum).Skip(20 + (page - 1) * 10).Take(10).ToList();
        //        }

        //        return list;
        //    }
        //}

        public IActionResult Detail(int boardNum)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.id = HttpContext.Session.GetString("USER_LOGIN_KEY");
            //using (var db = new BoardSystemContext())
            //{
            //    Board board;
            //    IEnumerable<Comment> commentList;
            //    try
            //    {
            //        board = db.Boards.FirstOrDefault(n => n.BoardNum.Equals(boardNum));
            //        db.Entry(board).Entity.BoardViews = board.BoardViews + 1;
            //        db.SaveChanges();
            //        commentList = db.Comments.ToList().Where(d => d.BoardNum.Equals(boardNum));
            //        ViewBag.commentList = commentList;
            //    } catch {
            //        return RedirectToAction("Error", "Home");
            //    }

            //    return View(board);
            //}
            return View();
        }

        public IActionResult Add()
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.id = HttpContext.Session.GetString("USER_LOGIN_KEY");
            return View();
        }

        [HttpPost]
        public IActionResult Add(Board model)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return Redirect("Index");
           // return View(model);
        }

        public IActionResult Edit()
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

    
        public IActionResult Delete(int boardNum)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            //using (var db = new BoardSystemContext())
            //{
            //    Board board;
            //    try
            //    {
            //        board = db.Boards.Find(boardNum);
            //        db.Boards.Remove(board);
            //        db.SaveChanges();
            //    }
            //    catch
            //    {
            //        return RedirectToAction("Error", "Home");
            //    }

            //    return Redirect("Index");
            //}
            return View();
        }

        public IActionResult DeleteComment(int boardNum, int commentNum)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            //using (var db = new BoardSystemContext())
            //{
            //    Comment comment;
            //    try
            //    {
            //        comment = db.Comments.Find(commentNum);
            //        db.Comments.Remove(comment);
            //        db.SaveChanges();
            //    }
            //    catch
            //    {
            //        return RedirectToAction("Error", "Home");
            //    }
            //    return Redirect("Detail?boardNum=" + boardNum);
            //}
            return View();
        }

        [HttpPost]
        public IActionResult AddComment(Board board)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            //string commentContents = Request.Form["CommentContents"].ToString();
            //string userId = Request.Form["UserId"].ToString();
            //int boardNum = int.Parse(Request.Form["BoardNum"].ToString());
            //Comment comment = new Comment
            //{
            //    BoardNum = boardNum,
            //    CommentContents = commentContents,
            //    UserId = userId
            //};
            //using (var db = new BoardSystemContext())
            //{
            //    try
            //    {
            //        db.Comments.Add(comment);
            //        db.SaveChanges();
            //    }
            //    catch
            //    {
            //        return RedirectToAction("Error", "Home");
            //    }

            //    return Redirect("Detail?boardNum="+ boardNum);
            //}
            return View();
        }

    }
}

Board/BoardSystem/Views/Board/Add.cshtml
@model BoardSystem.Models.Board

<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        <form class="form-horizontal" method="post" id="dataAddForm" asp-controller="Board" asp-action="Add">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label>題目</label>
                <input type="text" class="form-control" asp-for="BoardTitle" placeholder="題目入力" />
                <span class="text-danger" asp-validation-for="BoardTitle"></span>
            </div>
            <div class="form-group">
                <textarea class="form-control" asp-for="BoardContents" placeholder="内容入力"></textarea>
                <span class="text-danger" asp-validation-for="BoardContents"></span>
            </div>

            <div class="form-group">
                <button type="submit" onclick="dataAction()" class="btn btn-primary">投稿</button>
            </div>
</form>
    </div>
    <div class="col-lg-4"></div>
</div>

<script>
    function dataAction() {
        var arrayData = $('#dataAddForm').serializeArray();
        var userId = @ViewBag.id;
        $.ajax({
            type: "post",
            dataType: "json",
            url: "http://localhost:1455/api/Boards/",
            data: {
                "BoardTitle": arrayData[0].value,
                "BoardContents": arrayData[1].value,
                "UserId": userId
            },
            success: function (result) {
                console.log(result);

            }
        });
    }
</script>

Board/BoardSystem/Views/Board/Detail.cshtml
@using Microsoft.AspNetCore.Http
@model BoardSystem.Models.Board

<div class="row">
    <div class="col-lg-12" id="title">
        
    </div>
</div>

<div class="row" id="deleteButton">
    <div class="col-lg-10">
        <div class="panel panel-default" id="board">


        </div>
        @*@if (Context.Session.GetString("USER_LOGIN_KEY").Equals(@Model.UserId) || Context.Session.GetString("USER_LOGIN_KEY").Equals("root"))
        {
            <div class="panel-footer">
                <a class="btn btn-primary" asp-controller="Board" asp-action="Delete" asp-route-boardNum="@Model.BoardNum">削除</a>
            </div>
        }*@
    </div>
</div>
<div class="row">
    <div class="col-lg-10">
        <form class="form-horizontal" id="commentForm" method="post" action="" >
            <div class="form-group">
                <table>
                    <tr><th>
    <textarea class="form-control" name="CommentContents" id="CommentContents" placeholder="内容入力"></textarea>
    <span class="text-danger"></span>
</th>
                    <th><button type="submit" onclick="addValue()" class="btn btn-primary">コメント入力</button></th></tr>
                </table>
                
                <input type="hidden" name="UserId" id="UserId" value="" />
                <input type="hidden" name="BoardNum" id="BoardNum" value="" />
            </div>
            <div class="form-group">
                
            </div>
        </form>
    </div>
    <table class="table table-bordered" id="commentTable">
        <tr>
            <th>ユーザー</th>
            <th>コメント</th>
            <th>日付</th>
        </tr>
         
    </table>

</div>
<script>
    var root = "root";
    var boardContents;
    frmUrl = location.href;
    varCut = frmUrl.indexOf("?");
    varCheck = frmUrl.substring(varCut + 1);
    var varList = varCheck.split("&");
    forCount = varList.length;
    for (i = 0; i < forCount; i++) {
        eval(varList[i]);
    }
    
    $(window).load(function () {
        
        $.ajax({
            type: "get",
            dataType: "json",
            url: "http://localhost:1455/api/BoardContents?boardNum=" + boardNum,
            success: function (result) {
                $("#board").append('<div class="panel-heading" >題目：' + result.BoardTitle + '</div>' +
                    '<div class="panel-heading">ユーザー：' + result.UserId + '</div>' +
                    '<div class="panel-heading">日付：' + result.BoardDate + '</div>' +
                    '<div class="panel-heading">アクセス数：' + result.BoardViews + '</div>' +
                    '<div class="panel-body">' + result.BoardContents + '</div>'
                );
                $("#title").append('<h3 class="page-header" >題目 -' + result.BoardTitle + ' </h3>');
                if (userId == result.UserId || userId==root) {
                    $("#deleteButton").append('<a class="btn btn-primary" onclick="deleteBoard()">削除</a>');
                }
               
            }
        });
    });
</script>
<script>
    $(window).load(function () {
        $.ajax({
            type: "get",
            dataType: "json",
            url: "http://localhost:1455/api/Comments?boardNum=" + boardNum,
            success: function (result) {
                $.each(result, function (index, item) {
                    console.log(item);
                    $("#commentTable").append('<tbody><tr>' +
                        '<td>' + item.UserId + '</td>' +
                        '<td>' + item.CommentContents + '</td>' +
                        '<td>' + item.CommentDate + '</td>');
                    if (userId == item.UserId || userId == root) {
                        $("#commentTable").append('<td><a class="btn btn-primary" onclick="deleteComment(' + item.CommentNum + ')">削除</a></td>');
                    }
                    $("#commentTable").append('</tr></tbody>');

                });
            }
        });
    });
</script>
<script>
    var userId = @ViewBag.id;
    function addValue() {
        $("#UserId").attr("value", userId);
        $("#BoardNum").attr("value", boardNum);
        var commentContents = $("#CommentContents").val();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "http://localhost:1455/api/Comments",
            data: {
                "BoardNum": boardNum,
                "CommentContents": commentContents,
                "UserId": userId
            },
            success: function (result) {
                console.log(result);

            }
        });
    }
</script>
<script>
    function deleteBoard() {
        $.ajax({
            type: "delete",
            dataType: "json",
            url: "http://localhost:1455/api/Boards?boardNum=" + boardNum
            
        });
    }
</script>
<script>
    function deleteComment(commentNum) {
        $.ajax({
            type: "delete",
            dataType: "json",
            url: "http://localhost:1455/api/Comments?commentNum=" + commentNum

        });
    }
</script>

Board/BoardSystem/Views/Board/Index.cshtml
<a class="btn btn-warning " asp-controller="Board" asp-action="Add">投稿</a>
<table class="table table-bordered" id="table">

    <tr>
        <th>番号</th>
        <th>題目</th>
        <th>ユーザー</th>
        <th>日付</th>
        <th>アクセス数</th>
    </tr>



    @*@foreach (var board in Model)
    {
        <tr>
            <td>@board.BoardNum</td>
            <td><a asp-controller="Board" asp-action="Detail" asp-route-boardNum="@board.BoardNum">@board.BoardTitle</a></td>
            <td>@board.UserId</td>
            <td>@board.BoardDate</td>
            <td>@board.BoardViews</td>
        </tr>
    }*@

</table>
<script>
    $(window).load(function () {
        $.ajax({
            type: "get",
            dataType: "json",
            url: "http://localhost:1455/api/Boards",
            success: function (result) {
                $.each(result, function (index, item) {
                    console.log(item);
                    $("#table").append('<tr>' +
                        '<td>' + item.BoardNum + '</td>' +
                        '<td><a href="/Board/Detail?boardNum=' + item.BoardNum + '">' + item.BoardTitle + '</a></td>' +
                        '<td>' + item.UserId + '</td>' +
                        '<td>' + item.BoardDate + '</td>' +
                        '<td>' + item.BoardViews + '</td>' +
                        '</tr>');
                });
            }
        });
    });
</script>

<script>
    var page = 0;
    var work = true;
    $(window).scroll(function () {
        if (work && $(window).scrollTop() == $(document).height() - $(window).height()) {
            console.log(++page);
            getScrolled(page);
        }
    });

    function getScrolled(startNo) {
        $.ajax({
            url: "http://localhost:1455/api/Boards?page=" + startNo,
            type: "get",
            dataType: "json",
            success: function (result) {
                console.log(result);

                let length = result.length;
                if (length <= 0) {
                    work = false;
                }
                if (work || length > 0) {
                    console.log("loop");
                    $.each(result, function (index, item) {
                        console.log(item);
                        $("#table").append('<tr>' +
                            '<td>' + item.BoardNum + '</td>' +
                            '<td><a href="/Board/Detail?boardNum=' + item.BoardNum + '">' + item.BoardTitle + '</a></td>' +
                            '<td>' + item.UserId + '</td>' +
                            '<td>' + item.BoardDate + '</td>' +
                            '<td>' + item.BoardViews + '</td>' +
                            '</tr>');
                    });
                }
            }
        });
    }
</script>